[package]
name = "peer-discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = "1.0.188"

[dependencies.mongodb]
version = "2.7.0"
features = ["tokio-sync"]